---
- name: create gns3 user
  ansible.builtin.user:
    name: gns3
    shell: /bin/bash
  become: true

- name: create source code directory
  ansible.builtin.file:
    path: "{{ src_dir }}"
    state: directory
