---
- name: get and install dependencies
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python3-venv
      - pkg-config
  become: true

- name: get and install pipx
  ansible.builtin.pip:
    name: pipx
    break_system_packages: true
  become: true

- name: get and install
  community.general.pipx:
    name: gns3-server
    version: "{{ gns3_version | default(omit) }}"
    state: install
  notify:
    - restart gns3
  become: true
  become_user: gns3

- name: create directory for configuration file
  ansible.builtin.file:
    path: /etc/xdg/GNS3
    state: directory
    owner: gns3
    group: gns3
  become: true

- name: create configuration file
  ansible.builtin.copy:
    src: gns3_server.conf
    dest: /etc/xdg/GNS3/gns3_server.conf
    owner: gns3
    group: gns3
  notify:
    - restart gns3
  become: true

- name: create systemd unit file
  ansible.builtin.copy:
    src: gns3.service
    dest: /etc/systemd/system/gns3.service
  notify:
    - restart gns3
  become: true

- name: enable and start service
  ansible.builtin.systemd:
    name: gns3
    enabled: true
    state: started
  become: true
