---
- name: git clone ubridge (master branch)
  ansible.builtin.git:
    repo: https://github.com/GNS3/ubridge.git
    dest: "{{ src_dir }}/ubridge"
  register: ubridge_source

- block:
    - name: make ubridge
      community.general.make:
        chdir: "{{ src_dir }}/ubridge"

    - name: make install ubridge
      community.general.make:
        chdir: "{{ src_dir }}/ubridge"
        target: install
      become: true
  when: ubridge_source is changed
